// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello.proto
// Protobuf Java Version: 4.29.1

package net.n.example.high_concurrent_java_server.draft.gRPC.proto;

public final class GreetingProto {
  private GreetingProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */ 4, /* minor= */ 29,
        /* patch= */ 1, /* suffix= */ "", GreetingProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface HelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * 
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     * 
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code HelloRequest}
   */
  public static final class HelloRequest extends com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HelloRequest)
      HelloRequestOrBuilder {
    private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */ 4, /* minor= */ 29,
          /* patch= */ 1, /* suffix= */ "", HelloRequest.class.getName());
    }

    // Use HelloRequest.newBuilder() to construct.
    private HelloRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private HelloRequest() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest.class,
              net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";

    /**
     * <code>string name = 1;</code>
     * 
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }

    /**
     * <code>string name = 1;</code>
     * 
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest)) {
        return super.equals(obj);
      }
      net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest other =
          (net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest) obj;

      if (!getName().equals(other.getName()))
        return false;
      if (!getUnknownFields().equals(other.getUnknownFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code HelloRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:HelloRequest)
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest.class,
                net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest.Builder.class);
      }

      // Construct using
      // net.n.example.high_concurrent_java_server.draft.gPRC.proto.GreetingProto.HelloRequest.newBuilder()
      private Builder() {

      }

      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloRequest_descriptor;
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest getDefaultInstanceForType() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest
            .getDefaultInstance();
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest build() {
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest buildPartial() {
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest result =
            new net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest(
                this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(
          net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest) {
          return mergeFrom(
              (net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest other) {
        if (other == net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest
            .getDefaultInstance())
          return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private java.lang.Object name_ = "";

      /**
       * <code>string name = 1;</code>
       * 
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HelloRequest)
    }

    // @@protoc_insertion_point(class_scope:HelloRequest)
    private static final net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE =
          new net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest();
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloRequest> PARSER =
        new com.google.protobuf.AbstractParser<HelloRequest>() {
          @java.lang.Override
          public HelloRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<HelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HelloReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     * 
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     * 
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString getMessageBytes();
  }
  /**
   * <pre>
   * The response message containing the greeting.
   * </pre>
   *
   * Protobuf type {@code HelloReply}
   */
  public static final class HelloReply extends com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HelloReply)
      HelloReplyOrBuilder {
    private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC, /* major= */ 4, /* minor= */ 29,
          /* patch= */ 1, /* suffix= */ "", HelloReply.class.getName());
    }

    // Use HelloReply.newBuilder() to construct.
    private HelloReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private HelloReply() {
      message_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply.class,
              net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";

    /**
     * <code>string message = 1;</code>
     * 
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }

    /**
     * <code>string message = 1;</code>
     * 
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply)) {
        return super.equals(obj);
      }
      net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply other =
          (net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply) obj;

      if (!getMessage().equals(other.getMessage()))
        return false;
      if (!getUnknownFields().equals(other.getUnknownFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * <pre>
     * The response message containing the greeting.
     * </pre>
     *
     * Protobuf type {@code HelloReply}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:HelloReply)
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply.class,
                net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply.Builder.class);
      }

      // Construct using
      // net.n.example.high_concurrent_java_server.draft.gPRC.proto.GreetingProto.HelloReply.newBuilder()
      private Builder() {

      }

      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.internal_static_HelloReply_descriptor;
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply getDefaultInstanceForType() {
        return net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply
            .getDefaultInstance();
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply build() {
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply buildPartial() {
        net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply result =
            new net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply(
                this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(
          net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply) {
          return mergeFrom(
              (net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply other) {
        if (other == net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply
            .getDefaultInstance())
          return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private java.lang.Object message_ = "";

      /**
       * <code>string message = 1;</code>
       * 
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string message = 1;</code>
       * 
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string message = 1;</code>
       * 
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>string message = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>string message = 1;</code>
       * 
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HelloReply)
    }

    // @@protoc_insertion_point(class_scope:HelloReply)
    private static final net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE =
          new net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply();
    }

    public static net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloReply> PARSER =
        new com.google.protobuf.AbstractParser<HelloReply>() {
          @java.lang.Override
          public HelloReply parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<HelloReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.n.example.high_concurrent_java_server.draft.gRPC.proto.GreetingProto.HelloReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloRequest_descriptor;
  private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_HelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloReply_descriptor;
  private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData =
        {"\n\013hello.proto\"\034\n\014HelloRequest\022\014\n\004name\030\001 "
            + "\001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t29\n\017Gr"
            + "eetingService\022&\n\010SayHello\022\r.HelloRequest"
            + "\032\013.HelloReplyBK\n:net.n.example.high_conc"
            + "urrent_java_server.draft.gPRC.protoB\rGre" + "etingProtob\006proto3"};
    descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_HelloRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_HelloRequest_descriptor, new java.lang.String[] {"Name",});
    internal_static_HelloReply_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_HelloReply_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_HelloReply_descriptor, new java.lang.String[] {"Message",});
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
